wip

diff --git a/.github/workflows/ci-pipeline.yml b/.github/workflows/ci-pipeline.yml
--- a/.github/workflows/ci-pipeline.yml
+++ b/.github/workflows/ci-pipeline.yml
@@ -21,7 +21,7 @@ jobs:
       - name: Calculate Dockerfile checksum
         id: dockerfile_hash
         run: |
-          DOCKERFILE_HASH=$(find ./ci/Dockerfile -type f -exec sha256sum {} \; | sha256sum | cut -d' ' -f1)
+          DOCKERFILE_HASH=$(find ./ci/conan-unittests -type f -exec sha256sum {} \; | sha256sum | cut -d' ' -f1)
           echo "Dockerfile hash: $DOCKERFILE_HASH"
           echo "::set-output name=hash::$DOCKERFILE_HASH"
 
@@ -35,24 +35,24 @@ jobs:
       - name: Pull Docker image (if exists in cache or registry)
         id: pull_image
         run: |
-          docker pull ghcr.io/${{ github.repository_owner }}/my-custom-image:latest || echo "Image not found"
+          docker pull ghcr.io/${{ github.repository_owner }}/conan-unittests:latest || echo "Image not found"
 
       - name: Build Docker image (if not pulled or cache miss)
         if: steps.pull_image.outcome == 'failure' || steps.cache_docker_image.outputs.cache-hit != 'true'
         run: |
-          docker build -t ghcr.io/${{ github.repository_owner }}/my-custom-image:latest -f ./ci/Dockerfile .
-          mkdir -p docker_image_cache && docker save ghcr.io/${{ github.repository_owner }}/my-custom-image:latest -o docker_image_cache/my-custom-image.tar
+          docker build -t ghcr.io/${{ github.repository_owner }}/conan-unittests:latest -f ./ci/conan-unittests .
+          mkdir -p docker_image_cache && docker save ghcr.io/${{ github.repository_owner }}/conan-unittests:latest -o docker_image_cache/conan-unittests.tar
 
       - name: Push Docker image to GHCR
         if: steps.pull_image.outcome == 'failure' || steps.cache_docker_image.outputs.cache-hit != 'true'
         run: |
-          docker push ghcr.io/${{ github.repository_owner }}/my-custom-image:latest
+          docker push ghcr.io/${{ github.repository_owner }}/conan-unittests:latest
 
   linux_unittests:
     needs: build_container
     runs-on: ubuntu-latest
     container:
-      image: ghcr.io/${{ github.repository_owner }}/my-custom-image:latest
+      image: ghcr.io/${{ github.repository_owner }}/conan-unittests:latest
       options: --user conan
     strategy:
       matrix:
